kind: Cluster
name: omni-contrib
talos:
  version: v1.7.6
kubernetes:
  version: 1.30.4
features:
  enableWorkloadProxy: true
  backupConfiguration:
    interval: 24h
patches:
  - name: cni
    file: patches/cni.yaml
---
kind: ControlPlane
machineClass:
  name: omni-contrib-controlplane
  size: 3
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
---
kind: Workers
name: workers
machineClass:
  name: omni-contrib-workers
  size: unlimited
